name: "Publish AhoiCpp Release to Luarocks"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    name: Luarocks Upload
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish to Luarocks
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: "ahoicpp.nvim"
          summary: "C++ project scaffolding for Neovim"
          detailed_description: |
            AhoiCpp automates some parts of the heavy lifting of C++
            and enables a smoother experience without having to leave
            Neovim to do stuff such as creating new projects, classes,
            manage external dependencies, compile, run,
            read and interpret errors and so on.
          labels: |
            neovim
            c++
            cmake
            build-system
            just-in-time-personal-software
          dependencies: |
            plenary.nvim
